"""Dependency-inverted ports. Implementations may use SDKs, SQLite, or fakes."""
from __future__ import annotations

from pathlib import Path
from typing import Any, AsyncIterator, Protocol, runtime_checkable

from .events import NormalizedEvent, NormalizedHarnessEvent
from .models import Capability, HarnessRequest, HarnessResult, ProcessResult, TestCommand, WorkflowSnapshot


@runtime_checkable
class AgentHarness(Protocol):
    async def start(self, request: HarnessRequest) -> HarnessResult: ...
    async def resume(self, request: HarnessRequest) -> HarnessResult: ...
    async def send(self, request: HarnessRequest) -> HarnessResult: ...
    async def stream(self, session_id: str) -> AsyncIterator[NormalizedHarnessEvent]: ...
    async def cancel(self, session_id: str) -> None: ...
    async def capabilities(self) -> list[Capability]: ...

@runtime_checkable
class WorkflowEngine(Protocol):
    def checkpoint_before(self, snapshot: WorkflowSnapshot, operation_id: str, kind: str) -> None: ...
    def checkpoint_after(self, snapshot: WorkflowSnapshot, operation_id: str, result_reference: str | None = None) -> None: ...
    def load(self, run_id: str) -> WorkflowSnapshot: ...

@runtime_checkable
class CheckpointStore(Protocol):
    def save_snapshot(self, snapshot: WorkflowSnapshot) -> None: ...
    def latest_snapshot(self, run_id: str) -> WorkflowSnapshot | None: ...

@runtime_checkable
class ArtifactStore(Protocol):
    def write_json(self, relative_path: str, value: Any) -> Path: ...
    def write_text(self, relative_path: str, content: str) -> Path: ...
    def append_event(self, event: NormalizedEvent) -> Path: ...

@runtime_checkable
class WorktreeManager(Protocol):
    def create_integration(self, run_id: str, commit_base: str) -> Path: ...
    def create_task(self, run_id: str, task_id: str, commit_base: str) -> Path: ...
    def commit_task(self, task_id: str, message: str) -> str: ...
    def integrate_task(self, task_id: str) -> None: ...

@runtime_checkable
class TestRunner(Protocol):
    def run(self, command: TestCommand, cwd: Path) -> ProcessResult: ...

@runtime_checkable
class SandboxRuntime(Protocol):
    def capabilities(self) -> list[Capability]: ...
    def prepare(self, role: str, repository: Path, worktree: Path | None = None) -> Path: ...
    def wrap_command(self, policy_path: Path, argv: list[str]) -> list[str]: ...

@runtime_checkable
class EventSink(Protocol):
    def emit(self, event: NormalizedEvent) -> None: ...

@runtime_checkable
class PromptProvider(Protocol):
    def prompt_for(self, role: str) -> str: ...

@runtime_checkable
class PromptPort(Protocol):
    async def ask(self, message: str) -> str: ...

@runtime_checkable
class EventRenderer(Protocol):
    def render(self, event: NormalizedEvent) -> None: ...
